sorokin_iurii/gesture
NikAshanin/HomeTasks pull request #10
Opened 2017-11-19 00:42 UTC by SoriUR

2017-11-19 10:48 UTC, NikAshanin requested changes

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/.swiftlint.yml
> +disabled_rules:
Ненадо менять этот файл и выключать правила.

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/.swiftlint.yml
> +#warning_threshold: 1
и это тоже раскоментировать

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +//                performSegue(withIdentifier: "TapBar", sender: nil)
закомментированные строки удалять

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +        alert.addAction(UIAlertAction.init(title: "Ok", style: .cancel, handler: { [weak self] (_) in
[weak self] _ in

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +    @objc func circleRecognized() {
private func

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +        alert.addAction(UIAlertAction.init(title: "Ok", style: .cancel, handler: { [weak self] (_) in
.init слово не обязательно. удали

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +    var firstTap: CGPoint?
между свойствами и методами нужна пустая строка

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +            if allCirclePoints.count > 1000 {
эм, а что это за проверка?

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +        if Double(count) > Double(allCirclePoints.count) * 0.98 {
эм, что это опять же?

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +            touchesEnded(touches, with: event)  // can i do that? or witch state should i use?
нет, вызывать самому эти методы нельзя. Нужно писать .failed и все

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +        return sqrt( (p2.x - p1.x)*(p2.x - p1.x) + (p2.y - p1.y)*(p2.y - p1.y))
между скобками нет пробела, между арифметическими операциями есть пробел

2017-11-19 10:48 UTC, NikAshanin commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +            let coords = (point.x-origin.x)*(point.x-origin.x) + (point.y-origin.y)*(point.y-origin.y)
этот кусок кода уже есть выше. вынести в метод

2017-11-19 15:58 UTC, vibe0508 requested changes
Метод определения мне понравился, свежо 👍 
Надо устранить ряд вопросов по коду и понять, зачем фейлиться при количестве точек больше тысячи.
Также рекомендую некоторые вещи, типа центра, кешировать

2017-11-19 15:58 UTC, vibe0508 commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +        let radius = getRad(from: origin)
`getRad` - легко путается с радианами

2017-11-19 15:58 UTC, vibe0508 commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +        for point in array {
здесь на map и filter удобно сделать, попробуй

2017-11-19 15:58 UTC, vibe0508 commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +    private func checkPoints(in array: [CGPoint]) -> UInt {
согласен с Николаем, название не говорящее. Что то вроде `countConformingPoints(in: )` было бы понятнее

2017-11-19 15:58 UTC, vibe0508 commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +            touchesEnded(touches, with: event)  // can i do that? or witch state should i use?
зачем тебе вообще эта проверка? какой случай ты отсекаешь?

2017-11-19 15:58 UTC, vibe0508 commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +            if allCirclePoints.count > 1000 {
присоединяюсь к вопросу

2017-11-19 23:31 UTC, SoriUR commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +            touchesEnded(touches, with: event)  // can i do that? or witch state should i use?
Решил немного сделать UserFriendly и когда человек проведет круг, и приблизится достаточно близко к стартовой точке, автоматически начнется распознавание.

2017-11-19 23:33 UTC, SoriUR commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +            if allCirclePoints.count > 1000 {
если человек очень медленно ведет пальцем, то, в теории, может надобавляться очень много точек. С одной стороны можно было отслеживать время тача, но я сделал вот так.

2017-11-19 23:35 UTC, SoriUR commented on CustomGesture/CustomGesture/GestureViewController.swift
> +//                performSegue(withIdentifier: "TapBar", sender: nil)
коменты возможно понадобятся мне в будущем, оставляю лишь несущие информацию. Например в данном месте Алерт это чисто моя инициатива. Поэтому я оставил, то что изначально должно быть, обычный peformSegue, который всегда можно вернуть.

2017-11-19 23:37 UTC, SoriUR commented on CustomGesture/.swiftlint.yml
> +disabled_rules:
Думаю обсудить это лично. Разве пустая строка между методами не способствует читаемости кода? а swiftlint это запрещает

2017-11-20 06:18 UTC, vibe0508 commented on CustomGesture/.swiftlint.yml
> +disabled_rules:
swiftlint запрещает не это. он запрещает ненужные пробелы в конце строки.

2017-11-20 16:48 UTC, SoriUR commented on CustomGesture/.swiftlint.yml
> +disabled_rules:
oops, my bad

2017-11-27 12:17 UTC, vibe0508 approved these changes
Принято с моей стороны. Есть несколько моментов, которые можно улучшить

2017-11-27 12:17 UTC, vibe0508 commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +        if hasBeenFar, distance < 10 {
здесь `guard`

2017-11-27 12:17 UTC, vibe0508 commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
>              let firstTap = firstTap else {
здесь надо фейлиться

2017-11-27 12:17 UTC, vibe0508 commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
>              if sum < outterRadius, sum > innerRadius {
это логическое выражение, его результат можно сразу возвращать

2017-11-27 12:25 UTC, NikAshanin requested changes

2017-11-27 12:25 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +        let CircleRecognizer = UICircleGestureRecognizer(target: self,
CircleRecognizer объекты с маленькой буквы

2017-11-27 12:25 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +            self?.performSegue(withIdentifier: "TapBar", sender: nil)
tabbar, а не tapbar

2017-11-27 12:25 UTC, NikAshanin commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +        let outterRadius = radius*radius
эм, это же логически неверная операция. если радиусы по 100, то внешний радиус будет 10000, а внутренний 2500? что-то тут не так

2017-11-27 13:17 UTC, SoriUR commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +        let outterRadius = radius*radius
если внешний радиус 100, то квадрат его 10000. в формуле круга  R^2. а внутренний радиус половина внешнего. в квадрате, те *0.25

2017-11-27 16:50 UTC, NikAshanin requested changes

2017-11-27 16:50 UTC, NikAshanin commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +        let outterRadius = radius*radius
а зачем нам квадрат радиуса? И что за формула круга еще с R^2? Знаю только  pi*R*R
http://www.webmath.ru/poleznoe/formules9.php
Но вообще зачем нам это? Пиши логику в ответе на комментарий

2017-11-27 23:53 UTC, SoriUR commented on CustomGesture/CustomGesture/UICircleGestureRecognizer.swift
> +        let outterRadius = radius*radius
есть 2 круга, у большего radius. у меньшего radius*0.5
что бы проверить что человек провел по кругу, надо что бы все точки лежали между эти двумя кругами.
формула того, что точка принадлежит окружности (x0-x1)^2+(y0-y1)^2 = r^2
подставляя вместо x1, y1 координаты точки, а вместо x0, y0 координаты центра, и меняя знак = на <, > можно узнать лежат ли точки внутри или вне круга.
так я и проверяю что наши точки между двух кругов. 
outterRadius = radius^2
innerRadius = (radius*0.5)^2

2017-12-05 17:16 UTC, NikAshanin approved these changes

2022-03-27 18:31 UTC, closed without merging