guliamova_sitora/gesture
NikAshanin/HomeTasks pull request #14
Opened 2017-11-19 11:34 UTC by sitic96

CPD был удален из проекта т.к. при каждом запуске выдавал ошибку, устранить не получилось

2017-11-19 12:49 UTC, NikAshanin requested changes

2017-11-19 12:49 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +    }
swiftlint не работает у тебя, либо не установлен

2017-11-19 12:49 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +    @objc func ORecognized() {
private

2017-11-19 12:49 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +        self.performSegue(withIdentifier: "goToTabBarController", sender: self)
self не нужен

2017-11-19 12:49 UTC, NikAshanin commented on CustomGesture/CustomGesture/ORecognizer.swift
> +class ORecognizer: UIGestureRecognizer {
final

2017-11-19 12:49 UTC, NikAshanin commented on CustomGesture/CustomGesture/ORecognizer.swift
> +    let xRadius: CGFloat = 160, yRadius: CGFloat = 160
если радиус одинаков, то зачем их два?

2017-11-19 12:49 UTC, NikAshanin commented on CustomGesture/CustomGesture/ORecognizer.swift
> +    let centerPoint = CGPoint(x: 197, y: 320)
все свойства тут private должны быть

2017-11-19 12:49 UTC, NikAshanin commented on CustomGesture/CustomGesture/ORecognizer.swift
> +    // MARK: magic numbers
константы лучше вынести в enum

2017-11-19 12:49 UTC, NikAshanin commented on CustomGesture/CustomGesture/ORecognizer.swift
> +            //        firstTap = touches.first?.location(in: view?.superview)
закоментированный код удаляй и не пуш

2017-11-19 12:52 UTC, sitic96 commented on CustomGesture/CustomGesture/ORecognizer.swift
> +    let xRadius: CGFloat = 160, yRadius: CGFloat = 160
Чтобы в случае овала не добавлять дополнительные переменные и не менять код.

2017-11-19 15:46 UTC, vibe0508 requested changes

2017-11-19 15:46 UTC, vibe0508 commented on CustomGesture/CustomGesture/ORecognizer.swift
> +        if let firstTap = firstTap {
`guard`

2017-11-19 15:46 UTC, vibe0508 commented on CustomGesture/CustomGesture/ORecognizer.swift
> +            guard abs(firstTap.x - centerPoint.x) <= strokePrecision
соответственно присоединяешь к предыдущему `guard`

2017-11-19 15:46 UTC, vibe0508 commented on CustomGesture/CustomGesture/ORecognizer.swift
> +        if strokePart == 0
кто у кого скатывал: ты у Ирины или она у тебя?

2017-11-19 15:46 UTC, vibe0508 commented on CustomGesture/CustomGesture/ORecognizer.swift
> +    func isPointOnRadius(currentPoint: CGPoint) -> Bool {
`func isPointOnRadius(_ currentPoint: CGPoint) -> Bool`

2017-11-19 16:59 UTC, sitic96 commented on CustomGesture/CustomGesture/ORecognizer.swift
> +        if strokePart == 0
Весь код я писала полностью сама и код Ирины даже не видела, как и она мой т.к. я никому не показывала.

2017-11-19 20:04 UTC, vibe0508 commented on CustomGesture/CustomGesture/ORecognizer.swift
> +        if strokePart == 0
согласен, я оперся лишь на сходство "с первого взгляда". приношу свои извинения. Тогда вопрос другой: как появилась идея проверять последовательность секторов?

2017-11-19 22:56 UTC, sitic96 commented on CustomGesture/CustomGesture/ORecognizer.swift
> +        if strokePart == 0
Так нам так на занятие показали пример с Z и сказали попробовать сделать так же для О, но с 4 секторами

2017-11-20 06:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/ORecognizer.swift
> +        if strokePart == 0
окей

2017-11-20 16:12 UTC, NikAshanin requested changes

2017-11-20 16:12 UTC, NikAshanin commented on CustomGesture/CustomGesture.xcodeproj/project.pbxproj
> -			runOnlyForDeploymentPostprocessing = 0;
давай добавляй обратно. завтра посмотрим почему так

2017-11-20 16:12 UTC, NikAshanin commented on CustomGesture/CustomGesture.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 3.0;
пора обновлять xcode)

2017-11-20 16:12 UTC, NikAshanin commented on CustomGesture/CustomGesture/ORecognizer.swift
> +    override func touchesBegan(_ touches: Set<UITouch>,
между методами давай пустую строку добавлять

2017-11-20 20:36 UTC, sitic96 commented on CustomGesture/CustomGesture.xcodeproj/project.pbxproj
> -			runOnlyForDeploymentPostprocessing = 0;
@NikAshanin я пока лучше не буду возвращать его, иначе нет возможности запустить проект и проверить его работоспособность

2017-11-24 16:42 UTC, closed without merging