general logic
NikAshanin/HomeTasks pull request #18
Opened 2017-11-20 04:02 UTC by SoriUR

2017-11-20 06:16 UTC, vibe0508 requested changes
Пока не пойдет. Есть ряд очень существенных недоработок:

- когда грузятся фильмы, твой главный поток **стоит и жде**т. интерфейс в этот момент больше похож на скриншот;
- **никогда** не вешай тяжелые операции в геттер;
- логика, данные и UI разделены без всякой системы. в твоей модели данных есть куча всего, чего в ней быть не должно (к примеру, загрузка по сети), и нет того, что там быть должно (валидация в конструкторе, преобразование строки в дату)

2017-11-20 06:16 UTC, vibe0508 commented on StarWars/StarWars/MyViewController.swift
> +    private func searchCharacter() {
я на лекции говорил о том, что в api есть поле search. тогда тебе фильтрация не понадобится

2017-11-20 06:16 UTC, vibe0508 commented on StarWars/StarWars/MyViewController.swift
> +        return characters.count
хоть и не было в ТЗ, хорошая идея разложить персонажей по секциям 👍

2017-11-20 06:16 UTC, vibe0508 commented on StarWars/StarWars/MyViewController.swift
> +        dateLabel.text = dateString
тут надо:
1. иметь 2 форматтера
2. первый форматтер находится внутри модели, а из модели торчит уже дата
3. второй форматтер настраивается один раз, во `viewDidLoad()`
4. в выводе должен быть только год (см. тз)

2017-11-20 06:16 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> -class ViewController: UIViewController {
уж сколько раз твердили миру, не заменяйте имеющиеся файлы своими. но тут пусть так останется, комменты иначе тяжело трекать

2017-11-20 06:16 UTC, vibe0508 commented on StarWars/StarWars/MyViewController.swift
> +        return characters[section].films.count
а вот тут все намертво зависнет

2017-11-20 06:16 UTC, vibe0508 commented on StarWars/StarWars/Character.swift
> +            fetchFilmNames()
**никогда** не помещай сетевые вызовы в геттерах. что видит другой программист? он видит свойство, которое он получил, положил в переменную и пошел дальше. а у тебя здесь загрузка на несколько секунд

2017-11-20 06:16 UTC, vibe0508 commented on StarWars/StarWars/Character.swift
> +        group.wait()
если у тебя это происходит на главном потоке, то он будет дружно стоять и ждать

2017-11-23 13:41 UTC, vibe0508 requested changes
уже почти то, что надо. остался только 1 момент серьезный

2017-11-23 13:41 UTC, vibe0508 commented on StarWars/StarWars/Character.swift
> +        return filmsData
зачем тебе две разных проперти?

2017-11-23 13:41 UTC, vibe0508 commented on StarWars/StarWars/Character.swift
> +                if let data = data, let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] {
guard

2017-11-23 13:41 UTC, vibe0508 commented on StarWars/StarWars/MyViewController.swift
> +            let group = DispatchGroup()
здесь группа не нужна, тк у тебя задачи не распараллеливаются.

2017-11-23 13:41 UTC, vibe0508 commented on StarWars/StarWars/MyViewController.swift
> +        return characters[section].films.count
больше не актуально

2017-11-23 13:41 UTC, vibe0508 commented on StarWars/StarWars/Character.swift
> +    func fetchFilms() {
современный подход состоит в том, чтобы не делать такие методы (которые делают что-то долго) синхронными. Вместо этого лучше принимать коллбэк

2017-11-23 13:41 UTC, vibe0508 commented on StarWars/.swiftlint.yml
> +#warning_threshold: 1
включи назад

2017-11-23 16:41 UTC, SoriUR commented on StarWars/StarWars/Character.swift
> +        return filmsData
что бы сделать фильмы только get.

2017-11-23 16:43 UTC, SoriUR commented on StarWars/StarWars/MyViewController.swift
> +            let group = DispatchGroup()
но фильмы же параллельно скачиваются

2017-11-27 16:04 UTC, vibe0508 approved these changes
твое решение с экстеншеном строки мне не нравится. но по сути задания - принято

2017-11-27 16:04 UTC, vibe0508 commented on StarWars/StarWars/Character.swift
>                      group.leave()
`group.leave()` не должен зависить от парсинга. иначе неверный формат одного ответа заблокирует все

2017-11-27 16:04 UTC, vibe0508 commented on StarWars/StarWars/MyViewController.swift
> +fileprivate extension String {
решение очень ограниченного применения. вот тебе не только год понадобится, или формат даты изменится, или еще что-то. слишком много всего в кучу свалено

2017-11-27 18:48 UTC, NikAshanin requested changes

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/Character.swift
> +class Character {
final

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/Character.swift
> +    func fetchFilms(callback: @escaping () -> Void) {
не, вот это точно не тут. у тебя сейчас сервис и модель в одном месте

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/Character.swift
> +        self.name = name ?? "?"
optional, неправильно так делать. твой интерфейс должен соответствовать api

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/Character.swift
> +    var films: [(String, String)] {
string, string? там тоже ведь объект вместо словаря

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/MyViewController.swift
> +class MyViewController: UIViewController {
final и наименование "MyViewController"? переименовать

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/MyViewController.swift
> +        var newUrl: URL?
не нужна

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/MyViewController.swift
> +            newUrl = URL(string: urlTemplate + String(validSearchText))
тут сразу return

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/MyViewController.swift
> +        return newUrl
тут return nil

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/MyViewController.swift
> +    override func viewDidLoad() {
лишнее

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/MyViewController.swift
> +        let year = dateString.year ?? "неизвестно каком"
эм, это как?

2017-11-27 18:48 UTC, NikAshanin commented on StarWars/StarWars/MyViewController.swift
> +fileprivate extension String {
не так, в отдельный файл и static let

2017-11-27 23:22 UTC, SoriUR commented on StarWars/StarWars/MyViewController.swift
> +fileprivate extension String {
переделал, теперь это extension к Date, который возвращает год. Плохо выбрал класс для extension.

2017-11-27 23:33 UTC, SoriUR commented on StarWars/StarWars/MyViewController.swift
> +        var newUrl: URL?
а как же отказ от множественных return?) Чисто для этого делалось.

2017-12-11 11:32 UTC, NikAshanin approved these changes

2022-03-27 18:31 UTC, closed without merging