ageev_mikhail/starwars/iteration_2
NikAshanin/HomeTasks pull request #20
Opened 2017-11-20 15:38 UTC by kylesp1995

2017-11-20 16:18 UTC, NikAshanin requested changes

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars.xcodeproj/project.pbxproj
> +			runOnlyForDeploymentPostprocessing = 1;
включай обратно

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars.xcodeproj/project.pbxproj
> +			runOnlyForDeploymentPostprocessing = 1;
обратно включай)

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/Films.swift
> +struct Films {
class

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/Films.swift
> +struct Films {
и наверное FILM без S

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/Staff.swift
> +struct Staff: Decodable {
class

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +class ViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate {
final

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +class ViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate {
UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate в extension вынеси

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +  @IBOutlet weak var nameStaffLabel: UILabel!
выровняй по левому краю

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +  var staff = Staff.init(name: "", filmsURL: [], url: "", filmsName: [], filmDate: [])
.init можно удалить

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +      serachTextField.delegate = self
search вместо serach

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +      if staff.filmsURL.isEmpty{ return 1
ох щи)
давай сделаем 
```swift
return staff.filmsURL.isEmpty ? 1 : staff.filmsName.count

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +        cell.textLabel?.text = staff.filmsName[indexPath.row]
юзай тернарные операторы

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +      dateformatter.dateFormat = "yyyy-MM-dd"
в отдельный файл сабклассом

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +    self.serachTextField.resignFirstResponder()
self не нужен

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +  func uploadInfo(){
все это вынеси в модель или сервис

2017-11-20 16:18 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +              for result in results{
слишком сложная цикломатическая сложность. Больше трех вложений нужно разбивать или нечитаемо

2017-11-20 16:42 UTC, vibe0508 requested changes
- избавляйся от ненужной вложенности (guard, else if etc)
- вынеси в твою модель работу с данными (парсинг даты). в идеале, твоя модель не должна создаваться при невалидной строке даты
- модель `Staff` - очень мутная. подумай о рефакторинге
- не храни `DispatchGroup`

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/Films.swift
> +struct Films {
это один фильм. надо или хранить дату в виде даты (`Date`) или получать через калькулируемый атрибут

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +  var staff = Staff.init(name: "", filmsURL: [], url: "", filmsName: [], filmDate: [])
тут скорее optional

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +    let downloadGroup = DispatchGroup()
не храни группу в своем объекте. таким образом, ты делаешь разные прогоны зависимыми друг от друга

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +      serachTextField.delegate = self
в storyboard

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
пустая строка между методами

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +        cell.textLabel?.text = ""
зачем тебе пустая ячейка?

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +      let dateformatter = DateFormatter()
храни форматтер в объекте или как глобальную переменную

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +      let date = dateformatter.date(from: staff.filmDate[indexPath.row])
это должно быть в модели

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +      uploadInfo()
ну upload'ом тут не пахнет

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +    self.serachTextField.resignFirstResponder()
self не нужен

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +      if let data = data {
guard

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +          if let count = failUpload as? Int, count == 0{ // Как лучше это записать, чтобы избежать ворнинга?
сразу каст делай, на 67 строчке. по ворнингу завтра посмотрим

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +          } else {
else if

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +                self?.staff.name = result["name"] as! String
не надо force cast

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +        if let data = data {
guard

2017-11-20 16:42 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +      self.downloadGroup.wait()
если используешь `group.notify()`, использование глобальной очереди становится ненужным

2017-11-20 17:50 UTC, kylesp1995 commented on StarWars/StarWars/Films.swift
> +struct Films {
@NikAshanin а если я все-таки хочу структуру?

2017-11-20 18:04 UTC, kylesp1995 commented on StarWars/StarWars/ViewController.swift
> +      dateformatter.dateFormat = "yyyy-MM-dd"
@NikAshanin не совсем понял

2017-11-20 18:09 UTC, kylesp1995 commented on StarWars/StarWars/ViewController.swift
> +        cell.textLabel?.text = ""
@vibe0508 при первом запуске мы же ничего не отображаем

2017-11-20 18:11 UTC, kylesp1995 commented on StarWars/StarWars/ViewController.swift
> +      uploadInfo()
@vibe0508 проблема в неправильном нэйминге?

2017-11-20 18:12 UTC, kylesp1995 commented on StarWars/StarWars/ViewController.swift
> +          if let count = failUpload as? Int, count == 0{ // Как лучше это записать, чтобы избежать ворнинга?
@vibe0508 это просто xcode тупил

2017-11-20 19:40 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +      dateformatter.dateFormat = "yyyy-MM-dd"
Вынести в отдельный файл, сделать там инициализатор и в этом классе просто использовать.

2017-11-20 19:44 UTC, NikAshanin commented on StarWars/StarWars/Films.swift
> +struct Films {
Думаю, что можешь сделать struct если хочешь. Нужно на личном опыте пережить эту боль со структурами)

Лично я стараюсь по-минимуму использовать структуры и ориентируюсь только на кейсы, которые рекомендует apple:

Examples of good candidates for structures include:

The size of a geometric shape, perhaps encapsulating a width property and a height property, both of type Double.
A way to refer to ranges within a series, perhaps encapsulating a start property and a length property, both of type Int.
A point in a 3D coordinate system, perhaps encapsulating x, y and z properties, each of type Double.

Можно отдельно обсудить тему моей боли, если будет интересно. Вкратце если, то код со структурами абсолютно не reusable, не кастомизируем, не расширяем. Любое изменение в коде, появление нового поля и тд влечет кучу проблем. Юзаю структуры только если там простые типы внутри типо Int, Float, Double.

2017-11-20 20:15 UTC, kylesp1995 commented on StarWars/StarWars/ViewController.swift
> +    let downloadGroup = DispatchGroup()
@vibe0508 по этому вопросу лучше оффлайн спрошу

2017-11-23 14:19 UTC, vibe0508 requested changes
убирай DispatchGroup из контроллера

2017-11-23 14:19 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +//    let dateformatter = DateFormatter()
комменты не коммитим

2017-11-23 14:19 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +    let downloadGroup = DispatchGroup()
не храни группу здесь

2017-11-23 14:19 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +    staff.arrayFilm.isEmpty ? (cell.textLabel?.text = "") : (cell.textLabel?.text = staff.arrayFilm[indexPath.row].title)
используй стандартный if

2017-11-23 14:19 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +      return staff.arrayFilm.isEmpty ? 1 : staff.arrayFilm.count
зачем тебе пустая ячейка?

2017-11-23 14:19 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +    guard staff.arrayFilm[indexPath.row].date != "Error" else{
проще было сделать дату optional

2017-11-23 14:19 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
> +    let year = ModifyDate().cutYear(date: staff.arrayFilm[indexPath.row].date)
незачем каждый раз инициализировать `ModifyDate()`. или храни этот объект у себя в контроллере, или вставь эту функциональность в `Film`

2017-11-23 14:19 UTC, vibe0508 commented on StarWars/StarWars/ViewController.swift
>            if let title = json["title"], let date = json["release_date"] {
`let title = json["title"] as? String` и тогда дальше не надо будет форс-кастить

2017-11-27 18:55 UTC, NikAshanin requested changes

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/Film.swift
> +class Film {
final

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/Film.swift
> +  var date: String = ""
var date = ""

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/Film.swift
> +  var title: String = ""
var title = ""

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/ModifyDate.swift
> +class ModifyDate {
final class DateHelper

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/ModifyDate.swift
> +  let dateformatter = DateFormatter()
static

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/ModifyDate.swift
> +    let year = calendar.component(.year, from: modifyDate!)
включи swiftlint, тут force unwrap

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/Staff.swift
> +struct Staff {
class и naming другой

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +//    let dateformatter = DateFormatter()
убирай комментарии

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +      return staff.arrayFilm.isEmpty ? 1 : staff.arrayFilm.count
зачем 1 когда ничего нет?

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +    self.dateOfFilmLabel.text = "Фильм вышел: \(year)"
self не нужен, swiftlint не работает

2017-11-27 18:55 UTC, NikAshanin commented on StarWars/StarWars/ViewController.swift
> +  func downLoad() {
выноси в отдельный файл - NetworkService

2017-12-18 06:35 UTC, closed without merging