First CustomGesture commit
NikAshanin/HomeTasks pull request #23
Opened 2017-11-21 16:13 UTC by grigory9

2017-11-27 16:14 UTC, vibe0508 requested changes
в основном мелкие ремарки. покажи во вторник демо

2017-11-27 16:14 UTC, vibe0508 commented on CustomGesture/CustomGesture/CircleGesture.swift
> +            return
fail?

2017-11-27 16:14 UTC, vibe0508 commented on CustomGesture/CustomGesture/CircleGesture.swift
> +        let xPos = currentPoint.x - (centerCircle?.x ?? 0)
почему optional? если есть дефолтное значение (0,0), то можешь сразу задать его

2017-11-27 16:14 UTC, vibe0508 commented on CustomGesture/CustomGesture/CircleGesture.swift
> +        if currentPosition < ((radius * radius) + (strokePrecision * strokePrecision))
что-то мне подсказывает, что сначала сложение/вычитание, а потом возведение в квадрат

2017-11-27 16:14 UTC, vibe0508 commented on CustomGesture/CustomGesture/CircleGesture.swift
> +            currentAngle = angleBetween(pointA: startPoint, pointB: currentPoint)
синтаксис не самый удобный для чтения

2017-11-27 16:14 UTC, vibe0508 commented on CustomGesture/CustomGesture/GestureViewController.swift
> +        let circleRecognizer = CircleRecognizer(target: self, action: #selector(self.circleTapPressed))
self в селекторе не нужен

2017-11-27 16:14 UTC, vibe0508 commented on CustomGesture/CustomGesture/TabBarController.swift
> +class TabBarController: UITabBarController {
нет смысла делать свой класс, если ничего не меняешь

2017-11-27 19:09 UTC, NikAshanin requested changes

2017-11-27 19:09 UTC, NikAshanin commented on CustomGesture/CustomGesture/AppDelegate.swift
> -    func application(_ application: UIApplication,
возвращай этот код)

2017-11-27 19:09 UTC, NikAshanin commented on CustomGesture/CustomGesture/CircleGesture.swift
> +    let strokePrecision: CGFloat = 80
тут с модификаторами доступа разберись, половина из этого private

2017-11-27 19:09 UTC, NikAshanin commented on CustomGesture/CustomGesture/CircleGesture.swift
> +    func angleForPoint(_ point: CGPoint) -> CGFloat {
в extension для CGFloat

2017-11-27 19:09 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +final class ViewController: UIViewController {
было нормальное название, стало плохое

2017-11-27 19:09 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +        self.view.addGestureRecognizer(circleRecognizer)
self не нужен

2017-11-27 19:09 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +        circleRecognizer.setCircle(center: self.view.center, radius: 120)
и тут self не нужен

2017-11-27 19:09 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +            self.present(tabBar, animated: true, completion: nil)
self не нужен

2017-11-27 19:09 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +        if let tabBar = storyboard?.instantiateViewController( withIdentifier: "testController" ) as? UITabBarController {
пробелы лишние 
storyboard?.instantiateViewController(withIdentifier: "testController")

2017-12-11 11:36 UTC, NikAshanin requested changes

2017-12-11 11:36 UTC, NikAshanin commented on CustomGesture/CustomGesture/CircleGesture.swift
> +    func setCircle(center: CGPoint, radius: CGFloat) {
init же вместо метода

2017-12-11 11:36 UTC, NikAshanin commented on CustomGesture/CustomGesture/CircleGesture.swift
> +    private var circleState: Int = 0
enum же?

2017-12-11 11:36 UTC, NikAshanin commented on CustomGesture/CustomGesture/CircleGesture.swift
> +    private var circleParth: Int = 0
paRTH?

2017-12-11 11:36 UTC, NikAshanin commented on CustomGesture/CustomGesture/CircleGesture.swift
> +        let xPos = currentPoint.x - (centerCircle.x )
зачем тут скобки?

2017-12-11 11:36 UTC, NikAshanin commented on CustomGesture/CustomGesture/CircleGesture.swift
> +        let yPos = currentPoint.y - (centerCircle.y )
и тут зачем скобки?

2017-12-11 11:36 UTC, NikAshanin commented on CustomGesture/CustomGesture/CircleGesture.swift
> +        if currentPosition < ((radius * radius) + (strokePrecision * strokePrecision))
и тут скобки половина не нужна

2017-12-11 11:36 UTC, NikAshanin commented on CustomGesture/CustomGesture/CircleGesture.swift
> +extension CircleRecognizer {
extension для CGPoint тут нужен

2017-12-11 11:36 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +        circleRecognizer.setCircle(center: view.center, radius: 120)
в init это

2017-12-11 11:36 UTC, NikAshanin commented on CustomGesture/CustomGesture/GestureViewController.swift
> +    @objc func circleTapPressed() {
private

2017-12-15 13:42 UTC, vibe0508 requested changes

2017-12-15 13:42 UTC, vibe0508 commented on Calculator/Calculator/CalculatorViewController.swift
> -final class CalculatorViewController: UIViewController {
откуда это здесь?!

2017-12-18 00:10 UTC, NikAshanin requested changes

2017-12-18 00:10 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> -final class CalculatorViewController: UIViewController {
да, нужно править. потом посмотрим

2017-12-19 11:45 UTC, closed without merging

2017-12-20 07:55 UTC, vibe0508 commented
так, а куда этот PR делся?