no message
NikAshanin/HomeTasks pull request #24
Opened 2017-11-23 11:32 UTC by kylesp1995

2017-11-27 19:10 UTC, NikAshanin commented
Пока не включишь swiftlint и CPD я смотреть не буду! Ну ад же сколько разных мелочей исправлять

2017-12-11 11:36 UTC, NikAshanin commented
Так ничего и не поправил

2017-12-18 00:09 UTC, NikAshanin requested changes
анализатор тут не включен. включай, затем правь ошибки и буду смотреть

2017-12-18 00:09 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +class CalculatorViewController: UIViewController {
final

2017-12-18 00:09 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +  @IBOutlet weak var dele: UIButton!
dele? что за название?

2017-12-18 00:09 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +  @IBOutlet weak var dele: UIButton!
private

2017-12-18 00:09 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +  @IBOutlet weak var resultLabel: UILabel!
private

2017-12-18 00:09 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +  var stack = Stack()
тут половина свойств private

2017-12-18 00:09 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +  @IBAction func buttonPressed(_ sender: UIButton) {
private

2017-12-18 00:09 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +  @IBAction func backButton(_ sender: Any) {
проверь всё на модификаторы доступа правильные

2017-12-18 00:09 UTC, NikAshanin commented on Calculator/Calculator/Stack.swift
> +class Stack{
final

2017-12-18 00:09 UTC, NikAshanin commented on Calculator/Calculator/Stack.swift
> +
анализатор тут не включен. включай, затем правь ошибки и буду смотреть

2017-12-18 06:17 UTC, kylesp1995 commented on Calculator/Calculator/Stack.swift
> +
@NikAshanin так я же все перезалил в другой пул реквест, сюда у меня почему-то не заливается

2017-12-22 23:10 UTC, closed without merging

2017-12-22 23:10 UTC, kylesp1995 commented
старый пул реквест