kositcin_alexander/calculator
NikAshanin/HomeTasks pull request #26
Opened 2017-11-23 12:45 UTC by kositcin

2017-11-27 19:22 UTC, NikAshanin requested changes

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> -final class CalculatorViewController: UIViewController {
был хороший файл, зачем его удалять

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +    private var isTyping = true
изначально должно быть false же

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +        // Initialization
тут не инициализация, да и комментарий не нужен. код должен быть self documented

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +    @IBAction func digitButtonPressed(_ sender: UIButton) {
private

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +            if mainLabelString.count <= 17 {
в константы, сейчас магия

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +    @IBAction func changeLabelsButtonPressed(_ sender: UIButton) {
private

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +    @IBAction func angleButtonPressed(_ sender: UIButton) {
private

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +    @IBAction func operationButtonPressed(_ sender: UIButton) {
private

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/Services/AlertService.swift
> +class AlertService {
Это AlertHelper, сервис должен хранить состояние, а у тебя только статичный метод

2017-11-27 19:22 UTC, NikAshanin commented on Calculator/Calculator/Services/StackService.swift
> +final class StackService {
опять же это не сервис

2017-11-27 19:24 UTC, kositcin commented on Calculator/Calculator/CalculatorViewController.swift
> -final class CalculatorViewController: UIViewController {
просто свой проект вставил полностью, удалив все, что было до этого

2017-11-27 19:29 UTC, kositcin commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +    private var isTyping = true
в моем случае изначально true, потому что считается, что пользователь уже ввел 0

2017-12-11 11:39 UTC, NikAshanin approved these changes

2022-02-05 12:41 UTC, closed without merging