sorokin_iurii/filmbrowser
NikAshanin/HomeTasks pull request #27
Opened 2017-11-24 11:20 UTC by SoriUR

2017-11-24 18:50 UTC, sitic96 commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +            Film(poster: #imageLiteral(resourceName: "E_1.jpg"), title: FilmSources.E1Title, descr: FilmSources.descriptions[0], likes: 0),
не лучше хранить в  assets?

2017-11-24 18:53 UTC, sitic96 commented on FilmBrowser/FilmBrowser/FilmTableViewCell.xib
> +        <image name="likeRed.png" width="200" height="200"/>
почему оно так странно залито изнутри?)

2017-11-24 19:41 UTC, SoriUR commented on FilmBrowser/FilmBrowser/FilmTableViewCell.xib
> +        <image name="likeRed.png" width="200" height="200"/>
ахах)

2017-11-24 19:42 UTC, SoriUR commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +            Film(poster: #imageLiteral(resourceName: "E_1.jpg"), title: FilmSources.E1Title, descr: FilmSources.descriptions[0], likes: 0),
возможно, я пока думаю как хранить) пока что так)

2017-11-24 19:49 UTC, sitic96 commented on FilmBrowser/FilmBrowser/FilmTableViewCell.xib
> +        <image name="likeRed.png" width="200" height="200"/>
@SoriUR https://material.io/icons/#ic_favorite попробуй отсюда

2017-11-27 16:42 UTC, vibe0508 requested changes
- разберись с переиспользованием ячеек. это чень важно
- переход нужно сделать без segue
- делегат должен работать с фильмом, тк твой detail контроллер знать не знает, откуда он вызван и какой там порядок

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/DetailViewController.swift
> +                          animations: nil,
сюда засовываешь `likesLabel?.text = String(describing: film.likes)` для полной красоты

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/DetailViewController.swift
> +        self.title = film.title
self не нужен

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/FilmTableViewCell.swift
> +        accessoryType = .disclosureIndicator
можно в xib сделать

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/FilmTableViewCell.swift
> +    func updateUI(filmData: Film) {
FYI. существует мнение, что ячейка не должна знать о модели. Что ты должен отдельно передатьвсе данные для заполнения. мнение однако спорное

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +                let indexPath = tableView.indexPathForSelectedRow else {
в этом случае sender - это ячейка. tableView подскажет тебе ее indexPath.

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +        if let cell = (Bundle.main.loadNibNamed("FilmTableViewCell", owner: self, options: nil)?.first) as? FilmTableViewCell {
нет, нет и еще раз нет. ты же делал предыдущее задание. ячейку получаем через dequeueReusableCell. иначе при большом количестве фильмов ты словишь прелестные тормоза.
Тебе нужно просто зарегать свой nib в таблице

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +            return UITableViewCell()
такого быть не должно

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +        cell?.isSelected = false
`deselectRow(for:)`

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +        performSegue(withIdentifier: "showInfo", sender: self)
работаем без segue

2017-11-27 16:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +        destination.index = indexPath.row
не надо передвать индекс, это портит переиспользуемость. в делегате ты можешь спокойно отдавать фильм и уже в контроллере определять индекс

2017-11-27 19:34 UTC, NikAshanin requested changes

2017-11-27 19:34 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/Film.swift
> +class Film: Decodable {
final

2017-11-27 19:34 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/FilmTableViewCell.swift
> +    func updateUI(filmData: Film) {
тут соглашусь, но представим, что Film это viewModel ячейки с private моделью
Я такое решение предлагал

2017-11-27 19:34 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +        let ip = IndexPath(row: index, section: 0)
ip - крайне плохое наименование

2017-11-27 23:58 UTC, SoriUR commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +        if let cell = (Bundle.main.loadNibNamed("FilmTableViewCell", owner: self, options: nil)?.first) as? FilmTableViewCell {
понял, поторопился...

2017-12-06 13:25 UTC, vibe0508 reviewed
не понял, где ты передаешь филь в экран деталей

2017-12-06 13:25 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +        navigationController?.pushViewController(detail, animated: true)
где ты сообщаешь своему `DetailViewController`, какой фильм показывать?

2017-12-06 18:24 UTC, SoriUR commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +        navigationController?.pushViewController(detail, animated: true)
в prepare(for segue:)

раньше передавал тут, но потом решил в prepare

destination.film = films[indexPath.row]
destination.delegate = self

можно совсем убрать prepare, и передавать в этом методе. но суть та же. 
Но остается вариант что, у меня будут segue в разные экраны, следовательно и разная логика подготовки.

2017-12-07 08:46 UTC, SoriUR commented on FilmBrowser/FilmBrowser/FilmsViewController.swift
> +        navigationController?.pushViewController(detail, animated: true)
Осознал и вернул 
detail.film = films[indexPath.row]
detail.delegate = self
сюда, и удалил prepare тк удалил performsegue

2017-12-11 12:45 UTC, NikAshanin requested changes

2017-12-11 12:45 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/FilmTableViewCell.xib
> +        <image name="imageView:XFL-xL-e04:image" width="200" height="200">
вот это что за дичь? такого не должно быть. фиксь

2017-12-11 15:15 UTC, vibe0508 approved these changes

2017-12-11 22:37 UTC, SoriUR commented on FilmBrowser/FilmBrowser/FilmTableViewCell.xib
> +        <image name="imageView:XFL-xL-e04:image" width="200" height="200">
понятия не имею, что это. Открыл этот файл на компе, там такого нет. запушил еще раз, пропало. Жду approved)

2017-12-18 00:05 UTC, NikAshanin approved these changes

2017-12-18 00:05 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/DetailViewController.swift
> +    @IBAction func likePressed(_ sender: UIButton) {
private

2022-03-27 18:31 UTC, closed without merging