kositcin_alexander/gesture
NikAshanin/HomeTasks pull request #64
Opened 2017-12-12 23:22 UTC by kositcin

2017-12-15 14:25 UTC, vibe0508 requested changes
твой рекогнайзер не должен быть связан с отрисовкой круга

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/Controllers/GestureViewController.swift
> +        let circleGestureRecognizer = CircleGestureRecognizer(circleView: circleView,
не должен рекогнайзер ничего знать о вью

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/Controllers/GestureViewController.swift
> +        print(view.center)
вывод для дебага не коммить

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private var circleView: CircleView
отписал выше

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
почему столько? не замечание пока, просто интересно

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +            return
fail

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +            return
fail

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +        let currentAngle = MathHelper.getAngle(of: currentPoint, to: circleView.center)
как то не читается, предлоги не те

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +        if currentValue < .pi {
для чего нужна эта проверка?

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/Services/MathHelper.swift
> +    static func getDistance(from point1: CGPoint,
сделай лучше extension CGPoint

2017-12-15 14:25 UTC, vibe0508 commented on CustomGesture/CustomGesture/Services/MathHelper.swift
> +    static func getAngle(of point: CGPoint,
аналогично

2017-12-19 11:12 UTC, kositcin commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
halfPathCheck - это прошел ли пользователь половину пути
halfPathDistance - это для описания области, в которую должен попасть пользователь на половине пути (потому что он вряд ли попадет ровно в точку с конкретными координатами)

2017-12-19 11:26 UTC, kositcin commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +        if currentValue < .pi {
если в данном случае пользователь пойдет в обратном направлении, то мы поймем, что половину пути он все-таки не прошел

2017-12-20 21:01 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
все равно непонятно. сделай рисунок и на нем покажи)

2017-12-20 21:02 UTC, kositcin commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
завтра можно?

2017-12-20 21:05 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
np

2017-12-22 09:28 UTC, NikAshanin requested changes

2017-12-22 09:28 UTC, NikAshanin commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    //private var circleView: CircleView
закомментированный код убирай

2017-12-22 09:28 UTC, NikAshanin commented on CustomGesture/CustomGesture/Services/MathHelper.swift
> +    static func convertAngle(angle: CGFloat,
Это что и зачем?

2017-12-22 09:28 UTC, NikAshanin commented on CustomGesture/CustomGesture/Views/CircleView.swift
> +    public let innerRadius: CGFloat = 100
public не нужен

2017-12-22 09:28 UTC, NikAshanin commented on CustomGesture/CustomGesture/Views/CircleView.swift
> +    public let outerRadius: CGFloat = 140
public не нужен

2017-12-22 09:28 UTC, NikAshanin commented on CustomGesture/CustomGesture/Views/CircleView.swift
> +    public let lineWidth: CGFloat = 3.0
public не нужен

2017-12-22 09:28 UTC, NikAshanin commented on CustomGesture/CustomGesture/Views/CircleView.swift
> +        drawCircle(with: innerRadius)
super тут нужен

2017-12-22 13:43 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
жду картинку

2017-12-23 12:20 UTC, kositcin commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
![image](https://user-images.githubusercontent.com/11396652/34319466-7524d46c-e7f4-11e7-8139-3df570583773.png)

1) стартовая точка
2) область около точки (3), описанная с помощью halfPathDistance
3) точка середины пути, который надо пройти
Если вдруг пользователь пойдет обратно и снова пересечет точку (3), переменная halfPathCheck снова станет false, как будто он точку (3) и не проходил

2017-12-23 12:25 UTC, kositcin commented on CustomGesture/CustomGesture/Services/MathHelper.swift
> +    static func convertAngle(angle: CGFloat,
Если вдруг у нас пользователь стартовал не в верхней точке окружности, то с помощью этого метода мы переводим величину угла точки, в которой сейчас находится пользователь, относительно стартовой точки

2017-12-23 20:28 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
ок. а почему 0.5 радиана? емнип, половина окружности - это 3.14...

2017-12-24 00:47 UTC, kositcin commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
0.5 это так сказать угловая длина области (2), выбрал в принципе не слишком большое и не слишком маленькое значение

2017-12-24 06:34 UTC, vibe0508 commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
тогда правь название, чтобы это было понятно)

2017-12-24 15:44 UTC, kositcin commented on CustomGesture/CustomGesture/CustomGestures/CircleGestureRecognizer.swift
> +    private let halfPathDistance: CGFloat = 0.5 // in radians
да, согласен, хреново назвал

2017-12-24 18:07 UTC, vibe0508 approved these changes

2022-02-05 12:41 UTC, closed without merging