kositcin_alexander/film_browser
NikAshanin/HomeTasks pull request #79
Opened 2017-12-21 06:20 UTC by kositcin

2017-12-21 16:52 UTC, NikAshanin commented
У тебя конфликты. Это нельзя смержить пока их не пофиксишь

2017-12-21 16:56 UTC, NikAshanin requested changes

2017-12-21 16:56 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/Models/Film.swift
> +    public let title: String
public не нужен

2017-12-21 16:56 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/Models/Film.swift
> +    public let description: String
public не нужен

2017-12-21 16:56 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/Models/Film.swift
> +    public let imageName: String
public не нужен

2017-12-21 16:56 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/Models/Film.swift
> +    public func addLike() {
public не нужен

2017-12-21 16:56 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/Models/Film.swift
> +    public func getLikes() -> Int {
public не нужен

2017-12-21 16:56 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/Models/Film.swift
> +    public func getLikes() -> Int {
вместо func сделать var

2017-12-21 16:56 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/Models/FilmsList.swift
> +final class FilmsList {
зачем тут целый класс? сразу в нужно месте вызывай внутренний метод

2017-12-21 16:56 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/ViewControllers/FilmsViewController.swift
> +        filmsTableView.delegate = self
всё в сториборде

2017-12-21 16:56 UTC, NikAshanin commented on FilmBrowser/FilmBrowser/ViewControllers/FilmsViewController.swift
> +        return FilmsList.films.count
тут ненадо обращаться к статичным методам и переменным

2017-12-23 14:02 UTC, kositcin commented
В моем случае не знаю как разобраться с конфликтом, лучше во вторник вопрос задам, потому что самому интересно.

2017-12-23 18:42 UTC, vibe0508 requested changes
с конфликтом во вт разберемся

2017-12-23 18:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/Services/FilmsInfoHelper.swift
> +    static let films = FilmsInfoHelper.getFilms()
просто getFilms()

2017-12-23 18:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/ViewControllers/FilmsViewController.swift
> +        return FilmsInfoHelper.films.count
не надо обращаться к глобальной переменной, заведи свою

2017-12-23 18:42 UTC, vibe0508 commented on FilmBrowser/FilmBrowser/ViewControllers/FilmsViewController.swift
> +        filmInfoViewController.film = FilmsInfoHelper.films[indexPath.row]
аналогично

2022-02-05 12:39 UTC, closed without merging