kositcin_alexander/starwars/iteration/2
NikAshanin/HomeTasks pull request #80
Opened 2017-12-21 09:22 UTC by kositcin

2017-12-21 10:05 UTC, timbog approved these changes

2017-12-21 16:51 UTC, NikAshanin requested changes

2017-12-21 16:51 UTC, NikAshanin commented on StarWars/StarWars/Controllers/MainViewController.swift
> +        filmsTableView.delegate = self
все делегаты в сториборде задавай

2017-12-21 16:51 UTC, NikAshanin commented on StarWars/StarWars/Controllers/MainViewController.swift
> +        loaderActivityIndicator.stopAnimating()
во viewdidload у тебя индикатор еще не крутится. останавливать его не нужно

2017-12-21 16:51 UTC, NikAshanin commented on StarWars/StarWars/Controllers/MainViewController.swift
> +    private func clearFilmYearLabel() {
зачем отдельный метод?

2017-12-21 16:51 UTC, NikAshanin commented on StarWars/StarWars/Controllers/MainViewController.swift
> +        clearFilmYearLabel()
оно по дефолту и так пустое будет. не нужный метод

2017-12-21 16:51 UTC, NikAshanin commented on StarWars/StarWars/Controllers/MainViewController.swift
> +            } else {
пустой else? что-то забыто

2017-12-21 16:51 UTC, NikAshanin commented on StarWars/StarWars/Controllers/MainViewController.swift
> +            self?.filmsTableView.reloadData()
тут нужно перейти на главный поток. Весь UI работает только на главном потоке

2017-12-21 16:51 UTC, NikAshanin commented on StarWars/StarWars/Services/NetworkService.swift
> +            return
а где completionBlock? он ожидается тут тоже

2017-12-22 13:55 UTC, vibe0508 approved these changes
в общем, Николай все написал, мне нечего дополнить

2017-12-22 13:55 UTC, vibe0508 commented on StarWars/StarWars/Services/NetworkService.swift
> +        group.notify(queue: DispatchQueue.main) {
достигаешь поставленной цели, но не явно,т к у тебя комплишен в комплишене

2017-12-23 13:04 UTC, kositcin commented on StarWars/StarWars/Controllers/MainViewController.swift
> +        clearFilmYearLabel()
я на всякий случай в коде прописываю, что label пустой, вдруг кто-то что-то изменит в сториборде
так стоит делать, или это считается лишним кодом?

2022-02-05 12:38 UTC, closed without merging