ready to check
NikAshanin/HomeTasks pull request #9
Opened 2017-11-19 00:18 UTC by SoriUR

2017-11-20 16:10 UTC, NikAshanin requested changes

2017-11-20 16:10 UTC, NikAshanin commented on Calculator/Calculator/Stack.swift
> +        func goForward() -> (Double, String?)? {
поехало что-то вправо

2017-11-20 16:10 UTC, NikAshanin commented on Calculator/Calculator/Stack.swift
> +//    func reset() {
убрать закоментированный код

2017-11-27 13:34 UTC, vibe0508 requested changes

2017-11-27 13:34 UTC, vibe0508 commented on Calculator/Calculator/Calculator.swift
> +    var reestablishingModel = false
что это означает?

2017-11-27 13:34 UTC, vibe0508 commented on Calculator/Calculator/Calculator.swift
> +            pendingFunction = resultIsPending ? pendingBinaryOperation!.fun : nil
реализация `resultIsPending` может поменяться в будущем. лучше действовать через if let

2017-11-27 13:34 UTC, vibe0508 commented on Calculator/Calculator/Calculator.swift
> +        case (.trigonometryOperation(let function), .some):
`case (.trigonometryOperation(let function),  let accumulatedValue?):`
и тогда не придется форс кастить

2017-11-27 13:34 UTC, vibe0508 commented on Calculator/Calculator/Calculator.swift
> +            if pendingBinaryOperation != nil {
if let

2017-11-27 13:34 UTC, vibe0508 commented on Calculator/Calculator/CalculatorViewController.swift
> +    var inTheMiddleOftyping = true
`isTyping` - старайся избегать длинных названий, если и так все понятно

2017-11-27 13:34 UTC, vibe0508 commented on Calculator/Calculator/CalculatorViewController.swift
> +        let multiplayer: CGFloat = traitCollection.horizontalSizeClass == .compact ? 0.7 : 0.9
`multiplier `?

2017-11-27 13:34 UTC, vibe0508 commented on Calculator/Calculator/CalculatorViewController.swift
> +    func selectOperationButton(with title: String, in view: UIView) {
второй параметр не используется

2017-11-27 13:34 UTC, vibe0508 commented on Calculator/Calculator/CalculatorViewController.swift
> +        radiansStateLabel.text = model.degreesMode ? "" : "Rad"
используй `isHidden`

2017-11-27 13:34 UTC, vibe0508 commented on Calculator/Calculator/Stack.swift
> +//    func reset() {
не пуш закомментированный код

2017-11-27 16:40 UTC, NikAshanin requested changes

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/.swiftlint.yml
> +#warning_threshold: 1
а чего так и не включено?

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/Assets.xcassets/darkGray.imageset/Contents.json
> +    {
договорились вроде как убрать это

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/Calculator.swift
> +class Calculator {
final

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/Calculator.swift
> +    var stack = Stack()
тут с приватностью внимательнее

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +    lazy var model = Calculator()
private?

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +    var buttonsArray: [UIButton] = []
private?

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +    lazy var model = Calculator()
и зачем ленивые вычисления для модели тут?

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +    var displayText = "0" {
private везде прочекай

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +extension Double {
либо private либо в отдельный файл

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +        var stringFromDouble = formatter.string(from: NSNumber(value: self))!
force unwrap убирай

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/CalculatorViewController.swift
> +        let formatter = NumberFormatter()
и NumberFormatter в static let

2017-11-27 16:40 UTC, NikAshanin commented on Calculator/Calculator/Stack.swift
> +        func goForward() -> (Double, String?)? {
поехало куда-то вправо

2017-12-06 13:06 UTC, vibe0508 reviewed
Некоторые вопросы остались проигнорированными

2017-12-06 13:06 UTC, vibe0508 commented on Calculator/Calculator/Calculator.swift
> +    var reestablishingModel = false
вопрос остался без ответа

2017-12-06 13:06 UTC, vibe0508 commented on Calculator/Calculator/Extensions/UIImage+formColor.swift
> +    convenience init?(color: UIColor, size: CGSize = CGSize(width: 1, height: 1)) {
приведи пример ситуации, когда ты будешь передавать другой размер?

2017-12-06 18:27 UTC, SoriUR commented on Calculator/Calculator/Calculator.swift
> +    var reestablishingModel = false
когда при нажатии кнопки undo и redo, вызываются методы которые пушат в стек операции, что бы не пушить их еще раз, ставлю этот флаг. тем самым логика остается но в стек не заносится.

2017-12-11 10:46 UTC, NikAshanin approved these changes

2017-12-11 10:46 UTC, NikAshanin commented on Calculator/Calculator/Calculator.swift
> +    var stack = Stack()
private

2017-12-11 10:46 UTC, NikAshanin commented on Calculator/Calculator/Calculator.swift
> +    var degreesMode = true
private

2017-12-11 10:46 UTC, NikAshanin commented on Calculator/Calculator/Calculator.swift
> +    var reestablishingModel = false
private

2017-12-11 15:04 UTC, vibe0508 approved these changes

2022-03-27 18:31 UTC, closed without merging